app = 'backend-golden-sandbar-3995'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  memory = '1gb'